#!/usr/bin/env python3
"""
Regenerates FUNCTION-MAP.md: every top-level function and exported symbol,
with the file and line it lives on. Run after any change that adds or moves
a function:   python3 tools/gen_map.py
The point is that finding code should cost one file read, not a dozen greps.
"""
import glob, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

FN = re.compile(r'^(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(')
CONST = re.compile(r'^(?:const|let|var)\s+([A-Z][A-Z0-9_]{2,})\s*=')
ROUTE = re.compile(r'path\s*===\s*"([^"]+)"')

files = sorted(glob.glob('[0-9][0-9]_*.js'))
rows, routes = [], []
for f in files:
    n = int(f[:2])
    for i, line in enumerate(open(f, encoding='utf-8', errors='replace'), 1):
        m = FN.match(line)
        if m: rows.append((m.group(1), f, i))
        m = CONST.match(line)
        if m: rows.append((m.group(1), f, i))
        for r in ROUTE.finditer(line):
            routes.append((r.group(1), f, i))

out = ['# Function Map', '',
       '_Generated by `tools/gen_map.py`. Do not edit by hand._', '',
       f'{len(rows)} top-level symbols across {len(files)} files.', '',
       '## Routes', '', '| path | file:line |', '|---|---|']
for p, f, i in sorted(set(routes)):
    out.append(f'| `{p}` | {f}:{i} |')
out += ['', '## Symbols', '', '| symbol | file:line |', '|---|---|']
for name, f, i in sorted(rows, key=lambda r: r[0].lower()):
    out.append(f'| `{name}` | {f}:{i} |')

open('FUNCTION-MAP.md', 'w', encoding='utf-8').write('\n'.join(out) + '\n')
print(f'FUNCTION-MAP.md: {len(rows)} symbols, {len(set(routes))} routes, {os.path.getsize("FUNCTION-MAP.md"):,} bytes')
